### ISSUE TITLE
mongodb version problem

### ISSUE THREAD

**Issue by fff** [lefthand/Node-JS-Bootstrap#1]
Thank you for your works!
the latest version of **mongodb** in npm repository is _"0.9.7-1.4"_,and **_ObjectId.getTimestamp()**_ is not shown in this version,these make the visite to url `/posts` fail

> TypeError: /Users/fff/workspace01/Node-JS-Bootstrap/views/posts/index.jade:22
>    20|     th Created
>    21|   - each post in posts
> > 22|     - postDate = post._id.getTimestamp().toDateString()
>    23|     tr
>    24|       td
>    25|         a(href='/post/#{post._id}') #{post.title} \n
> 
> Object 4f34c4e26da226b2e5000001 has no method 'getTimestamp'

any suggestion?

**Comment by fff** [comment]
It's OK, after repository address was corrected

**Comment by lefthand** [comment]
Glad you got it working.  I'll see if I can add some error handling to catch that in the future.
